version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app-network
    # Kết nối với NGINX qua mạng
    expose:
      - "3001"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: webapp
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - /home/chauzz/Cki_Linux/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount file cấu hình NGINX
      - ./frontend/build:/usr/share/nginx/html  # Mount thư mục build của frontend vào NGINX
    ports:
      - "8080:80"  # Mở cổng 80 cho NGINX
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
